main = "./src/index.ts"
name = "worker-relay"
compatibility_date = "2022-07-26"

kv_namespaces = [{ binding = "PRICINGS_KV", id = "<PROD_KV_ID>" }]

[triggers]
crons = ["*/9 * * * *"]

[vars]
PRICINGS_SERVICE_URL = "https://pricings-service.example.com"
NODE_ENV = "production"
